const std = @import("std");
const parser_mod = @import("parser.zig");
const ASTNode = parser_mod.ASTNode;
const ASTNodeType = parser_mod.ASTNodeType;

pub const CodeGen = struct {
    allocator: std.mem.Allocator,
    output: std.ArrayList(u8),

    pub fn init(allocator: std.mem.Allocator) CodeGen {
        return CodeGen{
            .allocator = allocator,
            .output = std.ArrayList(u8).init(allocator),
        };
    }

    pub fn deinit(self: *CodeGen) void {
        self.output.deinit();
    }

    pub fn generate(self: *CodeGen, program: *ASTNode) ![]const u8 {
        const writer = self.output.writer();

        try writer.writeAll("; This was generated by Y--'s compiler (ymmc)\n");
        try writer.writeAll("bits 64\n");
        try writer.writeAll("section .text\n\n");

        if (program.data == .Program) {
            for (program.data.Program.statements.items) |stmt| {
                try self.emitNode(stmt, writer);
            }
        }

        return self.output.toOwnedSlice();
    }

    fn emitNode(self: *CodeGen, node: *ASTNode, writer: anytype) !void {
        _ = self;
        switch (node.data) {
            .FuncDecl => |func| {
                try writer.print("global {s}\n", .{func.name});

                if (func.abi) |abi| {
                    try writer.print("; Calling convention override: {s}\n", .{abi});
                }

                try writer.print("{s}:\n", .{func.name});
                try writer.writeAll("    push rbp\n");
                try writer.writeAll("    mov rbp, rsp\n");

                if (func.body) |body| {
                    _ = body;
                }

                try writer.writeAll("    mov rsp, rbp\n");
                try writer.writeAll("    pop rbp\n");
                try writer.writeAll("    ret\n\n");
            },

            .VarDecl => |variable| {
                if (variable.reg_binding) |reg| {
                    try writer.print("    ; Bound variable '{s}' to hardware register {s}\n", .{ variable.name, reg });

                    try writer.print("    ; Operations on '{s}' will directly manipulate {s}\n", .{ variable.name, reg });
                } else {
                    try writer.print("    ; Stack variable '{s}'\n", .{variable.name});
                }
            },

            .StructDecl => |str| {
                try writer.print("; Struct definition: {s}\n", .{str.name});
                if (str.alignment) |align_bytes| {
                    try writer.print("; Align boundary: %align {}\n", .{align_bytes});
                }
            },

            .ReturnStmt => |ret| {
                if (ret.value) |val| {
                    _ = val;
                    try writer.writeAll("    ; Set return value in rax\n");
                }
            },

            else => {},
        }
    }
};