#include "codegen_c.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void print_indent(CodeGenerator* gen) {
    for (int i = 0; i < gen->indent_level; i++) {
        fprintf(gen->output, "    ");
    }
}

void codegen_init(CodeGenerator* gen, FILE* output) {
    gen->output = output;
    gen->indent_level = 0;
}

static void emit_node(CodeGenerator* gen, ASTNode* node);

static void emit_expression(CodeGenerator* gen, ASTNode* node) {
    if (!node) return;

    switch (node->type) {
        case AST_NUMBER:
            fprintf(gen->output, "%g", node->data.number_val);
            break;

        case AST_STRING:
            fprintf(gen->output, "\"%s\"", node->data.string_val);
            break;

        case AST_IDENTIFIER:
            fprintf(gen->output, "%s", node->data.identifier_name);
            break;

        case AST_BINARY:
            fprintf(gen->output, "(");
            emit_expression(gen, node->data.binary.left);
            fprintf(gen->output, " %s ", node->data.binary.op);
            emit_expression(gen, node->data.binary.right);
            fprintf(gen->output, ")");
            break;

        case AST_CALL:
            fprintf(gen->output, "%s(", node->data.call.callee);
            for (size_t i = 0; i < node->data.call.arg_count; i++) {
                emit_expression(gen, node->data.call.args[i]);
                if (i + 1 < node->data.call.arg_count) {
                    fprintf(gen->output, ", ");
                }
            }
            fprintf(gen->output, ")");
            break;

        case AST_ALLOC:
            fprintf(gen->output, "malloc(");
            emit_expression(gen, node->data.alloc_expr.size_expr);
            fprintf(gen->output, ")");
            break;

        case AST_SIZEOF:
            fprintf(gen->output, "sizeof(%s)", node->data.sizeof_expr.target_type);
            break;

        case AST_CAST:
            fprintf(gen->output, "(%s)(", node->data.cast_expr.target_type);
            emit_expression(gen, node->data.cast_expr.expr);
            fprintf(gen->output, ")");
            break;

        default:
            break;
    }
}

static void emit_node(CodeGenerator* gen, ASTNode* node) {
    if (!node) return;

    switch (node->type) {
        case AST_VAR_DECL:
            print_indent(gen);
            fprintf(gen->output, "double %s", node->data.var_decl.name);
            if (node->data.var_decl.initializer) {
                fprintf(gen->output, " = ");
                emit_expression(gen, node->data.var_decl.initializer);
            }
            fprintf(gen->output, ";\n");
            break;

        case AST_ALIAS_DECL:
            print_indent(gen);
            fprintf(gen->output, "// alias %s -> %s\n", node->data.alias_decl.alias_name, node->data.alias_decl.target_name);
            print_indent(gen);
            fprintf(gen->output, "#define %s %s\n", node->data.alias_decl.alias_name, node->data.alias_decl.target_name);
            break;

        case AST_FREE:
            print_indent(gen);
            fprintf(gen->output, "free(");
            emit_expression(gen, node->data.free_stmt.target_ptr);
            fprintf(gen->output, ");\n");
            break;

        case AST_IF:
            print_indent(gen);
            fprintf(gen->output, "if (");
            emit_expression(gen, node->data.if_stmt.condition);
            fprintf(gen->output, ") {\n");
            gen->indent_level++;
            emit_node(gen, node->data.if_stmt.then_branch);
            gen->indent_level--;
            print_indent(gen);
            fprintf(gen->output, "}");

            if (node->data.if_stmt.else_branch) {
                fprintf(gen->output, " else {\n");
                gen->indent_level++;
                emit_node(gen, node->data.if_stmt.else_branch);
                gen->indent_level--;
                print_indent(gen);
                fprintf(gen->output, "}\n");
            } else {
                fprintf(gen->output, "\n");
            }
            break;

        case AST_RETURN:
            print_indent(gen);
            fprintf(gen->output, "return ");
            if (node->data.return_stmt.value) {
                emit_expression(gen, node->data.return_stmt.value);
            }
            fprintf(gen->output, ";\n");
            break;

        case AST_BLOCK:
            for (size_t i = 0; i < node->data.block.stmt_count; i++) {
                emit_node(gen, node->data.block.statements[i]);
            }
            break;

        default:
            print_indent(gen);
            emit_expression(gen, node);
            fprintf(gen->output, ";\n");
            break;
    }
}

void codegen_generate(CodeGenerator* gen, ASTNode* program) {
    fprintf(gen->output, "// This C code was generated by Y Compiler (y-lang)\n");
    fprintf(gen->output, "#include <stdio.h>\n");
    fprintf(gen->output, "#include <stdlib.h>\n\n");
    fprintf(gen->output, "int main(int argc, char** argv) {\n");

    gen->indent_level = 1;
    if (program && program->type == AST_PROGRAM) {
        for (size_t i = 0; i < program->data.program.stmt_count; i++) {
            emit_node(gen, program->data.program.statements[i]);
        }
    }

    print_indent(gen);
    fprintf(gen->output, "return 0;\n");
    fprintf(gen->output, "}\n");
}